### ISSUE TITLE
Poročilo za predstavitev

### ISSUE THREAD

**Issue by jernejbanevec** [Dzankomelli/APPR-2018-19#2]
Zdravo!
Opazil sem, da se tvoje poročilo `projekt.Rmd` ne prevede. V kolikor nameravaš v četrtek predstaviti svoje dosedanje delo na projketu, je smiselno poročilo spraviti v obliko, ki se prevede. Opazil sem naslednje napake:
* Ko kličeš `vizualizacija.r`, pride do problema, saj moreš pred uvozom vizualizacije uvoziti tudi _uvoz_moje_datoteke.R_, kar storiš tako:
```R
{r uvoz_Timotej, message=FALSE, warning=FALSE}
source("uvoz/uvoz_moje_datoteke.R")
```
* V datoteki `README.md` nastavi pravo pot, da se bo lahko tvoje poročilo poganjalo kar s pomočjo orodja _Binder_. To storiš tako, da znotraj datoteke (v zgornjem delu) popraviš
```R
[![RStudio](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/jaanos/APPR-2018-19/master?urlpath=rstudio)
```
v 
```R
[![RStudio](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/Dzankomelli/APPR-2018-19/master?urlpath=rstudio)
```

Ko boš uredil prvo alinejo, lahko potem v poročilu izrišeš tudi grafe iz vizualizacije, npr:
```R
{r graf}
print(graf_terciarno_solanje)
```

**Comment by Dzankomelli** [comment]
najlepša hvala :D

**Comment by jaanos** [comment]
Trenutno imaš povezave tako:

https://github.com/Dzankomelli/APPR-2018-19/blob/36a9caf00bc8ddc999c2dcc280c7d09141b59bb0/README.md#L5-L6

Prva povezava torej še vedno kaže na vzorčni repozitorij, tako da tudi tukaj popravi uporabniško ime. Ker je datoteki s poročilom ime `projekt.Rmd` (z malo začetnico!), naj bo tako tudi v povezavi (kot je bilo prej). Pri drugi povezavi lahko na konec dopišeš *RStudio*, da bo jasno, za kaj gre.

**Comment by jaanos** [comment]
Pri meni pride do težave pri uvozu datoteke `diplomanti.csv`. Nisem čisto prepričan, kaj je narobe, a je vendarle bolje, če za branje datotek namesto funkcij `read.*` (s piko) uporabljaš funkcije `read_*` (s podčrtajem) iz knjižnice `readr`. Datoteko lahko potem prebereš tako:
```R
diplomanti <- read_delim('podatki/diplomanti.csv', ';', skip=3, na=c(' ', '-'),
                         locale=locale(encoding='Windows-1250', decimal_mark='.'),
                         col_names=c('Leto', 'Regija', 'Meritev', 'Stevilo'))
```

V poročilu kličeš `vizualizacija.R`, a ima program v mapi `vizualizacija` končnico `.r` (mala črka!). Da bo delovalo povsod, ustrezno popravi v poročilu. Da se ti ne bodo v poročilo izpisovala opozorila, v glavo bloka kode za uvoz (in po potrebi še drugod) dodaj parameter `warning=FALSE` (tako kot že pri vizualizaciji).
