### ISSUE TITLE
Deljenje stevil

### ISSUE THREAD

**Issue by Dzankomelli** [Dzankomelli/APPR-2018-19#3]
Pozdravljeni!

Pri oblikovanju tabele za analizo in prikaz na grafu, sem želel izračunati razmerje med ljudmi, ki živijo v določeni regiji in številu otrok vključenih v vrtce. V 126 vrstici (uvoz_moje_datoteke.r) želim ti dve vrednosti deliti, a mi R javi napako 'In Ops.factor(Otroci, Vsi) : ‘/’ not meaningful for factors'. To sem želel popraviti tako, da sem spremenil v as.numeric in prav tako v as. integer, in mi v enem stolpcu deluje normalno, v drugem pa mi vrednosti popolnoma spremeni.  Če pogledam 'typeof' elementov v teh dveh stolpcih je že od začetka nastavljen na 'integer' vendar sem vseeno poskusil tako. Prosil bi vas, za kakšen nasvet kako bi lahko rešil nastalo težavo.

Najlepša hvala in lep pozdrav,
Timotej Giacomelli

**Comment by jernejbanevec** [comment]
Zdravo!
Za preverjanje tipa posameznega stolpca uporabljaj funkcijo `class`, ki tu vrne vrednost stolpca `razmerje$Vsi` vrednost `factor`:
```r
> class(razmerje$Vsi)
[1] "factor"
```
Prav tako za spreminjanje tipa posameznega stolpca v numerični tip raje uporabi funkcijo [`parse_number`](https://www.rdocumentation.org/packages/readr/versions/1.3.1/topics/parse_number)  iz knjižice `readr` (ta funkcija pa lahko spreminja tudi v druge tipe `parse_integer`, `parse_character`, ...). Ker ima stolpec `Otroci` že vrednost integer lahko problematično vrstico popraviš tako:
```r
razmerje <- transform(razmerje, Indeks=(Otroci/parse_integer(Vsi)))
```
Se ti pa splača tip tega stolpca spremeniti že prej na celoštevilski, tako da pozneje ta pretvorba ni potrebna.
