### ISSUE TITLE
analiza

### ISSUE THREAD

**Issue by Dzankomelli** [Dzankomelli/APPR-2018-19#4]
Pozdravljeni!

Želim narediti regresijsko premico za napovedovanje mojega BDP-ja. Dobivam veliko različnih napak, ki jih niti ne razumem dobro.  Težavo imam v delu analiza.r. Sem probal rešiti na več načinov vendar mi ni uspelo. Pustil sem tako, saj se mi zdi najbolj pravilno.  Iskreno bi vas prosil za pomoč.

LP

**Comment by jernejbanevec** [comment]
Pozdrav!
Do problemov prihaja, ker sta stolpca `BDP` in `Leto` razpredelnice `bruto_slovenija1` tipa _factor_. V kolikor to popraviš, napovedovanje tvojega `BDP`-ja deluje:
```R
bruto_slovenija1 <- bruto_slovenija1 %>% mutate(Leto = parse_integer(Leto), BDP = parse_number(BDP))
prileganje <- lm(BDP ~ Leto, data = bruto_slovenija1)
predict(prileganje, data.frame(Leto=seq(2018,2020,1)))
```
Graf lahko narišeš tako kot smo to počeli na vajah:
```R
ggplot(bruto_slovenija1, aes(x=Leto, y=BDP)) + geom_point() + geom_smooth(method="lm", formula=y ~ x)
```

Poskusi pa `BDP` aproksimirati tudi s pomočjo polinoma 2. stopnje v spremenljivki Leto, tako se zdi prileganje podatkom boljše.
