### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by Dzankomelli** [Dzankomelli/APPR-2018-19#5]
Pozdravljeni!

Osebno menim, da je moja zaključna naloga končana. Prosim, da mi poveste, če naj kje še kaj preuredim, dodam ipd.

Hvala za odgovor in lep pozdrav,
Timotej Giacomelli

**Comment by jaanos** [comment]
Poročila mi trenutno ne prevede, saj v poročilu kličeš program `uvoz_moje_datoteke.r`, medtem ko ima datoteka v mapi `uvoz` končnico `.R` (velika črka!), tako da bo treba to poenotiti. Do problemov pride tudi pri uvozu podatkov: če uporabljaš funkcijo `read.csv2` (s piko), bo treba kodiranje znakov podati s parametrom `fileEncoding`. Bolje bi sicer bilo, da namesto te funkcije uporabljaš `read_csv2` (s podčrtajem - parametri so potem nekoliko drugačni, tako kot pri `read_delim`).

Na zemljevidih ti ene regije ne prikaže, saj se njeno ime v zemljevidu razlikuje od tistega v podatkih. Najbolje bo torej, da v zemljevidu nadomestiš ime *Notranjsko-kraška* s *Primorsko-notranjska*. Pri grafu z regresijo uporabljaš regresijsko premico, a podatki zelo očitno niso linearni. Svetujem, da morda raje poskusiš s kvadratno ali kubično funkcijo.

**Comment by Dzankomelli** [comment]
popravil sem končnico moje datoteke in kodiranje podal s parametrom fileEncoding.  Meni na zemljevidih prikaže vse regije, saj sem za opisani problem napisal : 
Slovenija$Regija <- gsub('Notranjsko-kraĹˇka', 'Primorsko-notranjska', Slovenija$Regija)
Na enem zemljevidu zgleda kot da te regije ni, saj sta regiji slučajno v isti skupini in sta zato iste barve.
Pri regresiji sem poskusil s polinomom vendar mi ne uspe. Sem gledal na več mestih kako bi to lahko naredil pa nisem uspel ugotoviti. Ali imate mogoče kakšen nasvet, kje bi lahko našel kakšne primere uporabe na kar bi se lahko skliceval?
lp

**Comment by Dzankomelli** [comment]
oziroma nekako sem aproksimiral, vendar nisem prepričan, da je pravilno.
lp

**Comment by jaanos** [comment]
Podatkov, uvoženih z napačno kodno tabelo, ne popravljaj v kodi, saj nimaš zagotovila, da se bodo povsod uvozili na enak napačen način. Namesto tega poskrbi za ustrezen uvoz zemljevida - pri funkciji `uvozi.zemljevid` podaj parameter `encoding="UTF-8"`. Potem lahko popraviš samo regiji z napačnimi imeni.

Za regresijo s kvadratnim polinomom (ali višje stopnje) lahko narediš tako, kot smo delali na vajah - pri `geom_smooth` podaš parameter npr. `formula=y ~ I(x^2) + x`.

**Comment by Dzankomelli** [comment]
Sem popravil manjkajoče stvari.
lp

**Comment by jaanos** [comment]
V redu, sem dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora, če se seveda še nisi. Če boš še kaj spreminjal, mi prosim javi, da posodobim povezavo.

**Comment by Dzankomelli** [comment]
Prosil bi, da popravite povezavo.
Najlepša hvala.

**Comment by jaanos** [comment]
Sem posodobil.
